### PR TITLE
Never use user input for web metrics

### LINKED ISSUE #397: Runaway HTTP-Metrics due to use of unsafe user-input or crafted URIs as metric labels
### Expected Behavior

When running a Micronaut application with CORS and Micrometer metrics enabled, the user-input URI (especially during CORS preflights) is **NOT** used as the fallback for the "uri" label of the `http.server.request` metric in cases where the target endpoint and its URI-template cannot be determined.

In general, the incoming URI should never be used as the `uri` label on the `http.server.request` metric, because it entails insecure user input. The label on the metric should remain empty or should be set to a fixed value, if the target endpoint and its URI-template cannot be determined. The URI may contain payload such as encoded IDs which potentially lead to a huge number of distinct values for the `uri` label on this metric, which doesn't scale in downstream components related to monitoring, e.g. the Prometheus scraping endpoint's payload grows over time, which slows down your Prometheus instance.

A similar thing applies to HTTP Client metrics, where a manually constructed URI (or the URI given by the user in a forwarding-proxy) should not be used as a metric label, because it grows the number of distinct values for that label, if the path is crafted manually and/or has parameters encoded into it.

### Actual Behaviour

In case of a CORS preflight, the URI from the request (including payload such as IDs) is used for the "uri" label of the `http.server.requests` metric, which leads to an ever-growing list of distinct values for this label.
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

In case of any random HttpClient request to any URI, the URI path is used as the "uri" label of the `http.client.requests` metric, which leads to an ever-growing list of distinct values for this label, if the path is manually crafted and/or has parameter values encoded into it.
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

In case of any random HttpClient request to any URI, the "Host" header of the request is used as the "host" label of the `http.client.requests` metric, which leads to an ever-growing list of distinct values for this label, in case this header payload is crafted manually or provided via an incoming request in a forwarding-proxy (in which case it's our own domain).
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

### Steps To Reproduce

Run these tests: https://github.com/Robin479/micronaut-bugs/tree/main/http-metrics/src/test/java/de/ooch/micronaut/bugs

### Environment Information

_No response_

### Example Application

https://github.com/Robin479/micronaut-bugs/tree/main/http-metrics/src/test/java/de/ooch/micronaut/bugs

### Version

3.4.3

### LINKED ISSUE #458: @ServerWebsocket annotation results in too many metrics and out of memory conditions
### Steps to Reproduce

1. Create a class with an annotation similar to this: @ServerWebSocket("/media/v1/conversation/{conversationId}/websocket") and appropriately annotated @OnOpen and @OnMessage methods.
2. Open websockets to this service with different values for conversationId
3. Check the metrics scrape endpoint. 

### Expected Behaviour
I think that duration of websocket sessions doesn't make sense as a metric, especially not compared with regular http requests. I originally thought there should be a single pair of metrics as below because parameterized websocket controller paths should be treated like http parameterized controller paths. I now think websocket endpoints simply shouldn't have these metrics.

http_server_requests_seconds_count{exception="none",method="POST",status="200",uri="/media/v1/conversation/{conversationId}/websocket",} 3.0
http_server_requests_seconds_sum{exception="none",method="POST",status="200",uri="/media/v1/conversation/{conversationId}/websocket",} 0.56403263

### Actual Behaviour
There are multiple pairs of metrics like this:
http_server_requests_seconds_count{exception="none",method="POST",status="200",uri="/media/v1/conversation/ID-1/websocket",} 3.0
http_server_requests_seconds_sum{exception="none",method="POST",status="200",uri="/media/v1/conversation/ID-1/websocket",} 0.56403263
http_server_requests_seconds_count{exception="none",method="POST",status="200",uri="/media/v1/conversation/ID-2/websocket",} 3.0
http_server_requests_seconds_sum{exception="none",method="POST",status="200",uri="/media/v1/conversation/ID-2} 0.56403263

Over time this results in us running out of memory.

** I have worked around the problem by setting the `micronaut.metrics.http.path` property to a path that excludes my websocket endpoint. **

### Environment Information

- **Micronaut Version:** 3.7.1
- **Micrometer Version:** 4.6.1

### Additional Information
https://github.com/micronaut-projects/micronaut-micrometer/tree/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web

I think you may need a WebsocketRequestMeterRegistryFilter like you have for client and server.

### PR DESCRIPTION
**Pull request by n0tl3ss**
* Use service ID instead of host to identify clients
* Fallback to a fixed unmatched URI when template is not found 

Fixes #458 and Fixes #397

### CODE REVIEW

File: micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java [hunk 1]
```diff
@@ -56,8 +59,15 @@ public ServerRequestMeterRegistryFilter(MeterRegistry meterRegistry) {
     }
 
     private String resolvePath(HttpRequest<?> request) {
-        Optional<String> route = request.getAttribute(URI_TEMPLATE, String.class);
-        return route.orElseGet(request::getPath);
+        Optional<Object> routeInfo = request.getAttribute(HttpAttributes.ROUTE_INFO)
```
Comment (graemerocher) [inline micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java:62]: change this to `request.getAttribute(HttpAttributes.ROUTE_INFO, UriRouteMatch.class)` and you can avoid the filter and the cast and change the return type to `Optional<String>`

**Review by graemerocher — CHANGES_REQUESTED** [review]

**Comment by frank-mueller-at-kiwigrid-com** [comment]
I'm new to Github, so please apologize if this is not the correct way to re-open a bug.
Please advise if I should do it in a different way.

After upgrading my Micronaut project to Micronaut Micrometer 5.8.0 the built-in metrics "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics seem to be broken.

**Environment**

- Micronaut BOM 
io.micronaut.platform:micronaut-platform:4.6.2
which resolves to
io.micronaut.micrometer:micronaut-micrometer-registry-prometheus:5.8.0
io.micrometer:micrometer-core:1.13.3
io.prometheus:simpleclient:0.16.0

- Micronaut app with 2 HTTP clients configured
Client A neither sets "micronaut.http.route.template" nor "micronaut.http.serviceId" to the request
Client B sets "micronaut.http.route.template" and "micronaut.http.serviceId" to the request

- Micronaut app configured to write web metrics using Prometheus

**Steps to reproduce**
- run your Micronaut App
- initiate an action that let Client A send a request and thus 
- initiate an action that let Client B send a request
- check the "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics at the "/prometheus" endpoint of your Micronaut App

**Expected**
You find metrics produced by both client.

**Actual**
You find metrics produced by Client A only. Or more general, you find metrics of those client that writes as the first to the metric. The same would happen if Client B goes first.

**Assumption**
With this bugfix, ClientRequestMetricRegistryFilter & WebMetricsPublisher only writes the "uri" and/or "serviceId" tag if the corresponding request attribute was set by the client.
In the given example, this behavior causes two write operations happen to the same metric with a different set of tags.
However the Prometheus client does not like that. 
See https://github.com/micrometer-metrics/micrometer/issues/877 and https://github.com/prometheus/client_java/issues/696

As I'm just a user of the built-in "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics I have no chance to change that behavior.

**Suggested fix**
As there seems to be different opinions about whether this is a problem in Prometheus client or in Micrometer Prometheus integration and since it unclear when the actual problem gets fixed, I suggest to fix it in Micrometer core:

Let ClientRequestMetricRegistryFilter & WebMetricsPublisher always write the "uri" and "serviceId" tag. If "micronaut.http.route.template" or "micronaut.http.serviceId" are missing at the request, use an artifical constants as tag value.

**Comment by sdelamo** [comment]
@frank-mueller-at-kiwigrid-com [create a separate issue](https://github.com/micronaut-projects/micronaut-micrometer/issues) if you think it is necessary
